### ISSUE TITLE
Folder Not Found

### ISSUE THREAD

**Issue by popeen** [popeen/Popeens-Subsonic#22]
From popeen/Popeens-DSub#41

> 'm copying and pasting the directory where my audio books are (C:\Users\mich\Google Drive\Plex Only Media\Audio Books) directly out of my Window's 10 File Explorer. However, Booksonic Server is unable to find that folder. I tried step by step to make this work, starting with C:\, then C:\Users\, then C:\Users\mich\, etc. It works with C:\Users\mich\Google Drive\, but C:\Users\mich\Google Drive\Plex Only Media\ fails.

**Comment by popeen** [comment]
I have been trying to reproduce this but on my Windows 10 machines the path works fine.
Since I cant reproduce it on any of my machines I'm thinking it's probably something related to you machine.

Have you tried navigating to the folder in for example cmd? 
I'm not sure exactly how Google Drive works but maybe it is showing you a folder that's not really there "physically"?

**Comment by madmoneymike5** [comment]
I opened a cmd folder and typed it in. It works.

Initially, I wanted to ask: 1. Is there a character limit for directory paths in your server software, and 2. Have you investigated the effect of spaces in folder names on your server software?

...however, I tested other directories outside of Google Drive and found then to work regardless of the length or spacing. I went back to testing folders inside of Google Drive's main folder and found that no subfolder of \Google Drive\ works. \Google Drive\ itself is found, but subfolders are not.

Any ideas why?

**Comment by popeen** [comment]
Hmm, that's interesting.

No, unfortunately I don't have any ideas at the moment but I will look in to it. If I find something I'll let you know.

**Comment by madmoneymike5** [comment]
This is preventing me from using the software because moving the audio
files to another directory is not an option at the moment. Very sad
because I've been scouring the internet looking for a streaming server
software that handles books, and when I finally found yours....

**Comment by popeen** [comment]
I've tried to reproduce the error by installing Google Drive but I can still use the path without problem, I also tried wih Plex but even then it's still working fine. 

Since I'm unable to reproduce it the problem is most likely something else on your system but without knowing what there is not much I can do about it so I'm closing this issue.

As a last resort I have a work around that might work for you, it's not particularly pretty but at least you might be able to get it working. What you could try is to share the folder on your network and then use the network location inside Booksonic. To be able to use a network share you need to follow these instructions.
https://popeen.com/2016/05/27/using-a-network-shared-folder-in-booksonic/

Should you find whats causing the problem I would love to hear about it.
