### ISSUE TITLE
Documentation/Developer information

### ISSUE THREAD

**Issue by tuxflo** [popeen/Popeens-Subsonic#24]
I really would like to help developing booksonic but don't know how to start.
For example I'd like to add a "Never played" Link in the home menu which should not be a big thing.
Would it  be possible to get an developer documenation that contains information on how to get started? Or maybe some informations about creating the .war file and how to debug it.

**Comment by popeen** [comment]
Sorry but no, I have no documentation.
The Booksonic server is still almost vanilla Subsonic so you might be able to find some documentation there.

As for building the project (including the war file), you can do it by running this command in the root of the project
mvn package -U

Make sure you have maven installed.
