### ISSUE TITLE
tag of 1.1release is on wrong commit

### ISSUE THREAD

**Issue by relaystar** [popeen/Popeens-Subsonic#44]
a043e59 is the commit you have actually tagged as 1.1release
but
0ee2baa = actually has the 1.1release in it.

The net problem with this is that if someone wishes to deploy a build stable versions and hence checks out and builds 1.1release they actually get a beta version, missing the most recent fixes and whilst also being complained at by the android app and the web interface.

**Comment by carverhaines** [comment]
This still appears to be an issue

**Comment by carverhaines** [comment]
For the automated builds, it would be best to create a new release 1.2 at commit 0ee2baa

**Comment by popeen** [comment]
This has now been fixed, sorry it took a while.
Next time the docker container is rebuilt it should use the latest version
